Jim bok update2
finos/open-source-readiness pull request #113
Opened 2023-03-13 02:32 UTC by jstclair2019

Updates to previous errors and new pages

2023-03-13 13:15 UTC, robmoffat commented
Maybe worth labouring ROI / TCO Proprietary vs OSS.  

One article referenced from GGI: https://www.itjungle.com/2021/02/15/weighing-the-hidden-costs-of-open-source/

2023-03-27 12:17 UTC, robmoffat requested changes

2023-03-29 22:57 UTC, jstclair2019 commented on docs/bok/Measurements/Estimation.md
> +-- RM:  Jim, I'm not sure how useful this article is going to be.   Software estimation is a huge, complex topic that it might be best not to get into!
OK @robmoffat so just to confirm. Does it need to be trimmed down or do we remove altogether? Otherwise I could provide a sample project estimation?

2023-03-30 08:38 UTC, robmoffat commented on docs/bok/Measurements/Estimation.md
> +-- RM:  Jim, I'm not sure how useful this article is going to be.   Software estimation is a huge, complex topic that it might be best not to get into!
Well, we discussed on Monday after I wrote this - it's a tricky area of software ( I have spent [a while on this myself](https://riskfirst.org/estimating/Start)).

You persuaded me on Monday that we should expand on this - if you think you can provide some useful information here to people that is relevant to organisations trying to embrace open source then have at it!

2023-04-19 10:15 UTC, robmoffat commented
shall we merge this?

2023-04-19 13:15 UTC, jstclair2019 commented
Sure!

 

 

Best Regards,

________________________

Jim St.Clair

Digital Innovation Advisor

Coordinated Care Inc

228-273-4893

Schedule a meeting:  <https://calendly.com/jim-stclair-03> https://calendly.com/jim-stclair-03

 

From: Rob Moffat ***@***.***> 
Sent: Wednesday, April 19, 2023 5:16 AM
To: finos/open-source-readiness ***@***.***>
Cc: Jim St.Clair ***@***.***>; Assign ***@***.***>
Subject: Re: [finos/open-source-readiness] Return On Investment (PR #113)

 

shall we merge this?

—
Reply to this email directly, view it on GitHub <https://github.com/finos/open-source-readiness/pull/113#issuecomment-1514482056> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AMEIY6UIW4746S6FKMGAPFTXB63MHANCNFSM6AAAAAAVYP7DOA> .
You are receiving this because you were assigned.  <https://github.com/notifications/beacon/AMEIY6VADCJT2A4DYKOL3H3XB63MHA5CNFSM6AAAAAAVYP7DOCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTS2IUUYQ.gif> Message ID: ***@***.*** ***@***.***> >



-- 
This email has been checked for viruses by AVG antivirus software.
www.avg.com

2023-07-18 12:42 UTC, closed without merging