Supply chain security
finos/open-source-readiness pull request #172
Opened 2023-09-11 11:30 UTC by robmoffat

2023-09-11 12:32 UTC, robmoffat commented
https://deploy-preview-172--open-source-readiness.netlify.app/docs/bok/Activities/Level-2/Supply-Chain-Security
https://deploy-preview-172--open-source-readiness.netlify.app/docs/bok/Artifacts/CVE

2023-09-14 18:52 UTC, psmulovics approved these changes

2023-09-14 20:43 UTC, josspo requested changes

2023-09-28 07:06 UTC, robmoffat commented
Lots of good suggestions for improving this PR in the DevOps Automation / Supply Chain Security meeting.  However, I am going to close this now and tackle in a separate PR after my holiday.

2023-09-28 07:06 UTC, merged