Update License-Management.md
finos/open-source-readiness pull request #267
Opened 2024-05-01 14:30 UTC by robmoffat

2024-05-01 19:56 UTC, psmulovics commented
"10:30:55 AM: TypeError: Cannot read properties of undefined (reading 'sort')"

2024-05-01 19:57 UTC, psmulovics commented on docs/bok/Activities/Level-2/License-Management.md
> +<BokTagList tag="License Compliance Management (Role)" filter="Training" />
supposed to be 
License Compliance Management (Activity)

2024-05-07 21:25 UTC, psmulovics requested changes
You have to fix that line

2024-05-15 19:57 UTC, psmulovics commented
@robmoffat

2024-05-16 13:00 UTC, robmoffat commented
done

2024-05-16 14:36 UTC, psmulovics approved these changes

2024-05-16 14:37 UTC, merged

2024-05-25 19:00 UTC, GITHUB01reo reviewed
Hadir

2024-05-25 19:02 UTC, GITHUB01reo reviewed
Approved