Created 8Knot Page
finos/open-source-readiness pull request #275
Opened 2024-06-10 10:33 UTC by robmoffat

2024-06-10 13:56 UTC, caradelia commented on docs/Presentations/8Knot.md
> +Presentation by Cali Dolfi to FINOS OSR SIG on June 5 2024.
Cali Dolfi, Red Hat

2024-06-10 13:57 UTC, caradelia requested changes, later dismissed
Looks good. Just one small revision

2024-06-19 07:16 UTC, robmoffat commented
hi @caradelia,

Can you update your review so I can merge?

thanks

2024-07-02 14:31 UTC, robmoffat commented
@finos/osr-maintainers can we get this reviewed and merged?

2024-07-14 12:46 UTC, psmulovics approved these changes

2024-07-14 12:47 UTC, merged