Some ROI-style discussion points from the roundtable
finos/open-source-readiness pull request #59
Opened 2022-08-31 10:33 UTC by robmoffat

for discussion

2022-10-07 15:52 UTC, mcleo-d requested changes
Hi @robmoffat - There are some minor changes needed to the text before merging. Hopefully straightforward. Thanks for the hard work here!

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- Does having an Open-Source presence materially affect hiring talent?  Is there a reflected benefit in working on Open-Source?
`Open-Source` should be `open source`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- Can you measure the amount of Open-Source code the organisation is consuming?
`Open-Source` should be `open source`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- Is there a way of justifying the OSPO based on risk-reduction around consuming Open-Source code?
`Open-Source` should be `open source`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- Does consuming Open-Source reduce the amount of proprietary code that an institution uses?  In which case, is there a cost-saving on license fees for using Open-Source?
`Open-Source` should be `open source`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- Often, an Open-Source library will contain _bugs_, discovered by developers internal to your organisation.  The default (only) option available is to take ownership of a copy of the library and mai
`Open-Source` should be `open source`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- There is a strong case for allowing Open-Source contribution in order to lighten the load of this maintenance and ownership.
`Open-Source` should be `open source`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- It should be possible to look at where an institution has contributed fixes to Open Source projects - measuring this might be a way to justify allowing Open Source contribution, since each time thi
`Open Source` should be `open source`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- Where an institution open-sources its own code, how much contribution occurs from outside the organisation?
`Open-Sources` should be `open sources`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- At the moment, financial institutions don't really have a React-level project, but nevertheless it would be useful to track external contribution.
`React-level` should be `React level`

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- For a project like [Perspective](), originally donated by JP Morgan, contributions are now being made both from committers external to JP Morgan and also alumni.
Perspective link missing

2022-10-07 15:52 UTC, mcleo-d commented on docs/goals-objectives/resources.md
> +- Often a firm will have strategic objectives which dovetail into open-source.  For example, if your firm wishes to publish APIs then the OSPO should be recognised as a part of achieving these.
`open-source` should be `open source`

2022-10-14 13:27 UTC, psmulovics approved these changes

2022-10-14 13:28 UTC, merged